---
- hosts: ubuntu
  tasks:
  - name: check iof URL is responding
    wait_for:
      host: localhost
      port: 81
      delay: 10
      timeout: 30
      state: started
      msg: "Web server is not running"
    ignore_errors: true
