---
- hosts: win
  tasks:
  - name: Install IIS
    win_feature:
      name: Web-Server
      state: present
  - name: Start IIS
    win_service:
      name: W3SVC
      state: started
      start_mode: auto
  - name: Copy Index.html
    template:
      src: /etc/ansible/playbooks/index.html
      dest: c:\inetpub\wwwroot\index.html
     
